apps/models/urls.py
# django
from django.conf.urls import url
from django.views.generic import TemplateView
# project
from apps.utils.views import PopupFormView
from . import views
from .forms import CityForm

urlpatterns = [
    url(
        r'^crea/ciudad$',
        PopupFormView.as_view(
            form_class=CityForm,
            template_name="forms/city-popup-form.html"
        ),
        name="create_city_popup"
    ),
    url(
        r'^crea/activo$',
        views.ActiveCreate.as_view(),
        name="create_active"
    ),
    url(
        r'^edita/activo/(?P<pk>.+)$',
        views.ActiveEdit.as_view(),
        name="edit_active"
    ),
    url(
        r'^relaciona/activo/(?P<pk>.+)$',
        views.ActiveRelate.as_view(),
        name="relate_active"
    ),
    url(
        r'^borra/activo/(?P<pk>.+)$',
        views.ActiveDelete.as_view(),
        name="delete_active"
    ),
    url(
        r'^bienvenido$',
        TemplateView.as_view(
            template_name='pages/initiative-success.html'
        ),
        name="welcome_initiative"
    ),
]

civics/urls.py
# Import django apps
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog
# Import contrib apps
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView
# Import custom apps
from apps.users.views import ActivationView
from apps.models.views import Resources

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include('apps.api.urls', namespace="api")),
    url(r'^jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

urlpatterns += i18n_patterns(
    url(r'^$', TemplateView.as_view(template_name='pages/front.html'), name="front"),
    url(r'^', include('apps.models.urls', namespace='modelforms')),

    # Static URLs
    url(r'^acerca$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    url(r'^recursos$', Resources.as_view(template_name='pages/resources.html'), name="resources"),
    url(r'^privacidad$', TemplateView.as_view(template_name='pages/privacy.html'), name="privacy"),

    # Registration URLs
    url(r'^activate/(?P<activation_key>\w+)/$', ActivationView.as_view(), name='registration_activate'),
    url(r'^registrate/$', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name="registration_register"),
    url(r'^me-olvide-el-pass', auth_views.password_reset, name='password_reset'),
    url(r'^confirma-pass/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name="password_reset_confirm"),
    url(r'^pass-cambiado/$', auth_views.password_reset_complete, name="password_reset_complete"),
    url(r'^pass/ok/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'', include('registration.backends.default.urls')),
    url(r'^', include('apps.users.urls', namespace="users")),

    # Contact form
    url(r'^contacta/', include('contact_form.urls')),
)

if settings.DEBUG == True:
  urlpatterns += static( settings.STATIC_URL, document_root = settings.STATIC_ROOT )
  urlpatterns += static( settings.MEDIA_URL,  document_root = settings.MEDIA_ROOT )

templates/forms/city-popup-form.html
{# Template to render a modelform #} {% extends 'layouts/single-fixed-column.html' %} {% load i18n %}
{% block body_classes %}popup-modelform--city{% endblock %}


{% block main %}
    {% include 'pages/title.html' with title=title %}
    {% if form.errors and not form.non_field_errors %}
        <p class="form-errors">
            {% if form.errors.items|length == 1 %}
                {% trans "Parece que hay un error en el formulario. Revísalo, por favor." %}
            {% else %}
                {% trans "Parece que hay errores en el formulario. Revísalo, por favor.." %}
            {% endif %}
        </p>
    {% endif %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="form-errors">
                {{ error }}
            </p>
        {% endfor %}
    {% endif %}
    <form enctype="multipart/form-data" method="post" class="form--city">
        {% csrf_token %}
        <div class="form-fields--city">
            {% include 'forms/field.html' with field=form.name %}
            {% include 'forms/field.html' with field=form.name_es %}
            {% include 'forms/field.html' with field=form.position %}
        </div>
        <input class="form__submit" type="submit" value="{% trans 'Envía' %}" />
    </form>
{% endblock %}

{% block page_scripts %}
    {{ form.media }}
{% endblock %}

templates/forms/field.html
{# Template to render a formfield #}

{% with field.name|slugify as fieldname %}

<div class="field--{{ fieldname }} {% if field.field.required %}required{% endif %}">
    <p class="field__label--{{ fieldname }}">
        {{ field.label }}
    </p>
    <p class="field__help--{{ fieldname }}">
        {{ field.help_text | safe }}
    </p>
    {% if field.errors %}
    <ul class="field__errors--{{ fieldname }}">
        {% for error in field.errors %}
          <li class="field__error--{{ fieldname }}">
              {{ error }}
          </li>
        {% endfor %}
    </ul>
    {% endif %}
    <p class="field__widget--{{ fieldname }}">
        {{ field }}
    </p>
</div>

{% endwith %}

templates/forms/fields-active.html
{# Template to render all fields in a form #}
{# Not included in form.html to be reusable (in the context of a composed form, for instance) #}
{% load i18n %}

<div class="form-fields--{{ form_class }}">
    <div class="fieldset--two-col">
        <div class="fieldset__left--two-col">
            {% include 'forms/field.html' with field=form.name %}
            {% if request.user.is_staff %}
                {% include 'forms/field.html' with field=form.user %}
            {% endif %}
            {% include 'forms/field.html' with field=form.email %}
            {% include 'forms/field.html' with field=form.description  %}
        </div>
        <div class="fieldset__right--two-col">
            {% include 'forms/field.html' with field=form.image  %}
            {% include 'forms/field.html' with field=form.website %}
        </div>
    </div>
    <div class="fieldset--inline">
        {% include 'forms/field.html' with field=form.perspective %}
        {% include 'forms/field.html' with field=form.perspective_alt %}
    </div>
    <div class="fieldset--inline">
        {% include 'forms/field.html' with field=form.category %}
        {% include 'forms/field.html' with field=form.agent %}
    </div>
    <div class="fieldset--two-col">
        <div class="fieldset__left--two-col">
            {% include 'forms/field.html' with field=form.city %}
        </div>
        <div class="fieldset__right--two-col">
            {% include 'forms/field.html' with field=form.address %}
        </div>
        <div class="fieldset__full--two-col">
            {% include 'forms/field.html' with field=form.position %}
        </div>
    </div>
    {% if request.user.is_staff %}
        <div class="fieldset--one-col">
            {% include 'forms/field.html' with field=form.featured %}
        </div>
    {% endif %}
</div>

templates/forms/fields-city.html
{# Template to render all fields in a form #}
{# Not included in form.html to be reusable (in the context of a composed form, for instance) #}
{% load i18n %}

<div class="form-fields--{{ form_class }}">
    {% include 'forms/field.html' with field=form.name %}
    {% include 'forms/field.html' with field=form.name_es %}
    {% include 'forms/field.html' with field=form.position %}
</div>

templates/forms/fields-relations.html
{# Template to render all fields in a form #}
{# Not included in form.html to be reusable (in the context of a composed form, for instance) #}
{% load i18n %}

<div class="form-fields--{{ form_class }}">
    <div class="fieldset--inline">
        {% include 'forms/field.html' with field=form.actives %}
    </div>
</div>

templates/forms/fields.html
{# Template to render all fields in a form #}
{# Not included in form.html to be reusable (in the context of a composed form, for instance) #}

<div class="form-fields--{{ form_class }}">
    {% for field in form %}
        {% include 'forms/field.html' with field=field form_class=form_class %}
    {% endfor %}
</div>

templates/forms/form-relations.html
{# Template to render a modelform #} {% load i18n %}

{% if form.errors and not form.non_field_errors %}
    <p class="form-errors">
        {% if form.errors.items|length == 1 %}
            {% trans "Parece que hay un error en el formulario. Revísalo, por favor." %}
        {% else %}
            {% trans "Parece que hay errores en el formulario. Revísalo, por favor.." %}
        {% endif %}
    </p>
{% endif %}

{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <p class="form-errors">
            {{ error }}
        </p>
    {% endfor %}
{% endif %}

<form enctype="multipart/form-data" action="{{ action }}" method="post" class="form--{{ form_class }} {{ action_class }}">
    {% csrf_token %}
    {% with 'forms/fields-'|add:form_class|add:'.html' as fields %}
        {% include fields with form_class=form_class %}
    {% endwith %}
    <input class="form__submit" type="submit" value="{{ submit_text }}" />
    <span class="form__cancel" onclick="history.go(-1)">
        {% trans 'Volver atrás' %}
    </span>
    <a class="form__cancel" href="{% url 'front' %}">
        {% trans 'Cancelar e ir al mapa' %}
    </a>
</form>

templates/forms/form.html
{# Template to render a modelform #} {% load i18n %}

{% if form.errors and not form.non_field_errors %}
    <p class="form-errors">
        {% if form.errors.items|length == 1 %}
            {% trans "Parece que hay un error en el formulario. Revísalo, por favor." %}
        {% else %}
            {% trans "Parece que hay errores en el formulario. Revísalo, por favor.." %}
        {% endif %}
    </p>
{% endif %}

{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <p class="form-errors">
            {{ error }}
        </p>
    {% endfor %}
{% endif %}

<form enctype="multipart/form-data" action="{{ action }}" method="post" class="form--{{ form_class }} {{ action_class }}">
    {% csrf_token %}
    {% with 'forms/fields-'|add:form_class|add:'.html' as fields %}
        {% include fields with form_class=form_class %}
    {% endwith %}
    <input class="form__submit" type="submit" value="{{ submit_text }}" />
    {% if action_class == 'form-edit' %}
        <a class="form__relate" href="{% url 'modelforms:relate_active' object_id %}">
            {% trans 'Edita las relaciones' %}
        </a>
        {% with 'modelforms:'|add:'delete_'|add:form__html_class as edit_url %}
        <a class="form__delete" href="{% url edit_url object_id %}">
            {% trans 'Borra este contenido' %}
        </a>
        {% endwith %}
    {% endif %}
    <span class="form__cancel" onclick="history.go(-1)">
        {% if not action_class == 'form-relate' %}
            {% trans 'Cancelar' %}
        {% else %}
            {% trans 'Volver atrás' %}
        {% endif %}
    </span>
    {% if action_class == 'form-relate' %}
        <a class="form__cancel" href="{% url 'front' %}">
            {% trans 'Cancelar e ir a tu perfil' %}
        </a>
    {% endif %}
</form>

templates/forms/language-switcher.html
{# Lang switcher #} {% load i18n utils %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}

<form class="lang-switcher" id="lang-switcher" action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
    <input name="next" type="hidden" value="{{ request.path | remove_i18n_prefix }}" />
    <select class="lang-switcher__select" name="language" onchange="document.querySelector('#lang-switcher').submit()">
        {% for language in languages %}
            <option value="{{ language.code }}"
             {% if language.code == LANGUAGE_CODE %} selected="selected" {% endif %}>
                {{ language.code }}
            </option>
        {% endfor %}
    </select>
</form>

templates/forms/regular-form.html
{# Template to render a modelform #} {% load i18n %}

{% if form.errors and not form.non_field_errors %}
    <p class="form-errors">
        {% if form.errors.items|length == 1 %}
            {% trans "Parece que hay un error en el formulario. Revísalo, por favor." %}
        {% else %}
            {% trans "Parece que hay errores en el formulario. Revísalo, por favor.." %}
        {% endif %}
    </p>
{% endif %}

{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <p class="form-errors">
            {{ error }}
        </p>
    {% endfor %}
{% endif %}

<form enctype="multipart/form-data" action="{{ action }}" method="post" class="form--{{ form_class }} {{ action_class }}">
    {% csrf_token %}
    {% with 'forms/fields-'|add:form_class|add:'.html' as fields %}
        <div class="form-fields--{{ form_class }}">
            {% for field in form %}
                {% include 'forms/field.html' with field=field form_class=form_class %}
            {% endfor %}
        </div>
    {% endwith %}
    <input class="form__submit" type="submit" value="{{ submit_text }}" />
</form>